name: Aliyun Docker Image Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # 开启 Docker CLI 的实验性功能，因为 docker manifest 命令需要它
    env:
      DOCKER_CLI_EXPERIMENTAL: enabled

    steps:
    - uses: actions/checkout@v4
    
    - name: Set Aliyun Docker Login
      # 记得在 GitHub Secrets 中配置好 ALIYUN_REGISTRY_PASSWORD
      run: docker login --username=princehaku@aliyun.com --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
    
    - name: Set Docker QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    
    - name: Build the Docker buildx
      run: docker buildx create --name container-builder --driver docker-container --bootstrap --use
    
    - name: Build and Push Image (Force V2 + GZIP)
      run: |
        docker buildx build . -f ./Dockerfile-server \
          --platform linux/amd64 \
          --output "type=image,name=registry.cn-hangzhou.aliyuncs.com/haku-docker/xiaozhi-esp32-server:latest,push=true,oci-mediatypes=false,compression=gzip,force-compression=true" \
          --provenance=false \
          --sbom=false